server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: yu-picture-backend
  mvc:
    pathmatch:
      # Spring Boot 2.6+ 且集成了 Swagger/Knife4j，这个配置通常是必需的
      # @RequestMapping("/api/**")    // ** 匹配多级路径
      # @GetMapping("/user/*/{id}")    // * 匹配单级路径
      matching-strategy: ant_path_matcher # 兼容旧的通配符模式：支持 *（匹配任意字符）、**（匹配多级路径）、?（单字符）
    # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB # 单个文件最大大小 默认 1MB; 抛出 MaxUploadSizeExceededException
      # max-request-size # 整个请求最大大小 默认10MB
  # profiles:
  #  active: local
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/cc_picture?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  # 空间图片分表
  shardingsphere:
    datasource:
      names: cc_picture
      cc_picture:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cc_picture
        username: root
        password: 123456
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: cc_picture.picture # 动态分表 逻辑表
            table-strategy:
              standard:
                sharding-column: spaceId # 分表键
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.zjcc.ccpicturebackend.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true
  # redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000 #连接超时时间（毫秒）
    password: 123456
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  # session配置
  # 使用 Redis 管理分布式 Session，更好地维护登录态;
  # 避免单机登录态，也避免每次重启服务器都要重新登陆
  session:
    store-type: redis
    # session 30天过期(服务端 Redis)
    timeout: 2592000
    # cookie 30 天过期(客户端浏览器)
    cookie:
      max-age: 2592000 # ← cookie 挪到这里(Spring Session 才认)
knife4j:
  enable: true
  production: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 关闭 [MP查询数据库时 将驼峰命名自动转换为下划线]
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL日志打印到控制台
  global-config: #全局配置
    enable-sql-runner: true # SqlRunner 配合 DynamicShardingManager 动态创建分表
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名(isDelete 为实体类属性名称)
      logic-delete-value: 1 # 逻辑已删除值。可选，默认值为 1
      logic-not-delete-value: 0 # 逻辑未删除值。可选，默认值为 0